### ISSUE TITLE
Make the api more safer

### ISSUE THREAD

**Issue by qicosmos** [3rdparty/eventuals-grpc#1]
Pass a method name to Call is not safe, do you have a plan to replace it with a function and it can be checked at compile time, more safer than string.

```
auto status = server->Serve<RouteGuide, Stream<RouteNote>, Stream<RouteNote>>(
    "RouteChat",
    "host.domain.com",
    [](auto&& call) {
      // ...
    });
```

to 

```
auto status = server->Serve<RouteGuide, Stream<RouteNote>, Stream<RouteNote>>(
    &RouteGuide::RouteChat,  //replace string name here
    "host.domain.com",
    [](auto&& call) {
      // ...
    });
```

**Comment by benh** [comment]
Hi @qicosmos, sorry for the delay here, we were busy updating the API to model [stout-eventuals](https://github.com/3rdparty/stout-eventuals).

We still pass a string as the method name which we validate at runtime (before you try and make the call). I'm not aware of whether or not `protoc` always generates something like `RouteGuide::RouteChat`, or do you need to add `option cc_generic_services = true;` to your .proto file? And is there a way to actually get the name of the method as a string from this type?

**Comment by benh** [comment]
Closing this for now as we still have safety at runtime as addressed in the comment above. Going forward we'll also plan on doing protoc generation which will help this further.
