### ISSUE TITLE
Subsequent writes issued from `.ready()` aren't sent until `.ready()` completes.

### ISSUE THREAD

**Issue by rjhuijsman** [3rdparty/eventuals-grpc#10]
Imagine we have a server like this:
```proto
service ExpensiveAccumulator {
  // Build some result out of a stream of datapoints. Each datapoint updates
  // our result - doing so is expensive (say it takes 15 seconds), so we want 
  // to receive each datapoints as early as possible!
  rpc Accumulate(stream Datapoints) returns (ExpensiveFinalResult) {}
}
```

Consider a client like this:
```c++
client.Call<...>("ExpensiveAccumulator.Accumulate")
  | Client::Handler()
        .ready([](auto& call) {
           datapoint1 = expensive_computation(1);  // This will take a while, say 20 seconds.
           call.Write(datapoint1);
           datapoint2 = expensive_computation(2);  // This will take a while, say 20 seconds.
           call.Write(datapoint2);
           datapoint3 = expensive_computation(3);  // This will take a while, say 20 seconds.
           call.Write(datapoint3);
        })
        .body(Sequence().Once([](auto& call, auto&& response) {
           // MARK 1: How long does it take to get here after .ready() completes?
        }));
```

Ideally, `MARK 1` is reached ~15 seconds after `ready()` returns, since it takes `Accumulate` 15 seconds to add the final datapoint to its result.

In our current implementation, however, it takes **~30 seconds** to get to `MARK 1` after `ready()` returns. The `Write(datapoint2)` and `Write(datapoint3)` calls have no effect (no message is sent) until _after_ `ready()` returns, which means `datapoint2` can't already be processed on the server while `datapoint3` is being computed on the client.

The reason for this is subtle: `.ready()` is [called](https://github.com/3rdparty/stout-grpc/blob/e34e61fa38849cae4c02e916dd5f466f641ff256/stout/grpc/client.h#L113) from the `start_callback_`, which runs [on the same `CompletionQueue`](https://github.com/3rdparty/stout-grpc/blob/e34e61fa38849cae4c02e916dd5f466f641ff256/stout/grpc/client.h#L467) as `write_callback_`. Since each `CompletionQueue` [is consumed by a single thread](https://github.com/3rdparty/stout-grpc/blob/e34e61fa38849cae4c02e916dd5f466f641ff256/stout/grpc/completion-pool.h#L23), `write_callback_` won't run until `ready()` completes.

The first `Write(datapoint1)` isn't affected by this, since when there are no prior writes still waiting to for a `write_callback_` to run [we call](https://github.com/3rdparty/stout-grpc/blob/e34e61fa38849cae4c02e916dd5f466f641ff256/stout/grpc/client.h#L332) `stream_->Write(...)` directly. Subsequent writes have to wait [until they're performed inside the `write_callback_`](https://github.com/3rdparty/stout-grpc/blob/e34e61fa38849cae4c02e916dd5f466f641ff256/stout/grpc/client.h#L182) however.

To fix this, we will likely want to re-work the structure of `client.h` to allow _many_ writes to be sent directly to `stream_->Write(...)` before the first callback to `write_callback_` starts running. This will complicate our bookkeeping, since we can no longer assume that any requests queued in [`write_datas_`](https://github.com/3rdparty/stout-grpc/blob/e34e61fa38849cae4c02e916dd5f466f641ff256/stout/grpc/client.h#L377) are awaiting a `stream_->Write()`.

CC @benh for prioritization.

**Comment by rjhuijsman** [comment]
Note that [the tests in `streaming.cc`](https://github.com/3rdparty/stout-grpc/blob/e34e61fa38849cae4c02e916dd5f466f641ff256/test/streaming.cc) currently rely on this behavior (no write getting removed from `client.h`'s `write_datas_` before `ready()` completes) to correctly test various concurrency edge cases. We'll need to reimplement these tests in a different way if we change this behavior.

**Comment by benh** [comment]
Closing this issue after the recent refactors.
