### ISSUE TITLE
`server.Finish()` shouldn't be called until all writes AND all reads are done

### ISSUE THREAD

**Issue by rjhuijsman** [3rdparty/eventuals-grpc#15]
Very related to #12 - an almost-identical issue exists in `server.h`.

Quoth [the docs about `Finish()`](https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_async_reader_writer_interface.html#aa4d3c649b88c7fb7cba918def8fd99bf):
> It is appropriate to call this method when either:
> 
> * all messages from the client have been received (either known implictly, or explicitly because a previous AsyncReaderInterface::Read operation with a non-ok result (e.g., cq->Next(&read_tag, &ok) filled in 'ok' with 'false'.
> * it is desired to end the call early with some non-OK status code.

Our `server.h` currently will call `Finish()` as soon as it knows that the last _write_ has happened (either through `Continuation::WriteAndFinish()` or `Continuation::Finish()`), but it doesn't pay attention to the _reads_.

As with #12 this hasn't led to issues so far, but it seems unwise to use the API out-of-spec.

**Comment by benh** [comment]
Closing this issue as the recent refactorings now require this to be performed by the end user not the library itself (just as grpc requires this to be performed by the end user not their library itself).
