### ISSUE TITLE
`StoutGrpcTest.BroadcastCancel` test failed

### ISSUE THREAD

**Issue by ArthurBandaryk** [3rdparty/eventuals-grpc#23]
![Screen Shot 2021-09-30 at 4 47 20 PM](https://user-images.githubusercontent.com/68085133/135467790-8034cfd8-4c4f-468f-854d-b7b04c2712d7.png)

**Comment by ArthurBandaryk** [comment]
We need to figure out the reason why this test fails.

**Comment by benh** [comment]
Closing this issue as `Cluster` is no longer a part of the library.
