### ISSUE TITLE
Build failure with the newest bazel

### ISSUE THREAD

**Issue by ArthurBandaryk** [3rdparty/eventuals-grpc#65]
With bazel 5.0.0 on macOS the build fails with the following traceback:
![Screen Shot 2022-02-01 at 1 52 00 PM](https://user-images.githubusercontent.com/68085133/151955648-eb11c4ba-48db-4525-983e-c4201f50238e.png)
On Ubuntu:
![Screen Shot 2022-02-01 at 1 56 10 PM](https://user-images.githubusercontent.com/68085133/151956198-509e1e95-2fd1-4de8-b212-86d65d8587b1.png)

That's why we need to figure out the reason.
For now we can use `.bazeliskrc` to specify older version of bazel  if we wanna our build work. (e.g 4.2.2).
```
USE_BAZEL_VERSION=4.2.2
```

**Comment by CodingCanuck** [comment]
It looks like this is happening on other repos as well: https://github.com/google/jax/issues/8440
